apiVersion: v1
kind: Service
metadata:
  name: vault-np
  namespace: vault
spec:
  ports:
  - name: https
    port: 8200
    protocol: TCP
    targetPort: 8200
    nodePort: 30200
  - name: https-internal
    port: 8201
    protocol: TCP
    targetPort: 8201
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
  sessionAffinity: None
  type: NodePort
